workflows:
  ios-project-debug:
    name: iOS debug
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "CatalogApp.xcodeproj"
        XCODE_SCHEME: "CatalogApp"
        IOS_DEPLOYMENT_TARGET: "13.0"
    scripts:
      - name: Install SPM Dependencies and SwiftLint
        script: |
          # Install SPM dependencies
          xcodebuild -resolvePackageDependencies -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME"

          CONFIG_FILE="${PROJECT_DIR}/CatalogApp/Resources/.swiftlint.yml"
          
          if [[ "$(uname -m)" == arm64 ]]; then
              export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftlint > /dev/null; then
            cd "${PROJECT_DIR}" # Change the working directory to the project root
            swiftlint --config "$CONFIG_FILE" --fix && swiftlint --config "$CONFIG_FILE"
          fi
          brew install swiftlint
      - name: Clean DerivedData
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Run SwiftLint
        script: |
          swiftlint
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - ul.frasha@gmail.com
