workflows:
  ios-project-debug:
    name: iOS debug
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "CatalogApp.xcodeproj"
        XCODE_SCHEME: "CatalogApp"
        IOS_DEPLOYMENT_TARGET: "13.0"
        PROJECT_DIR: "$PWD"
        CONFIG_FILE: "$PROJECT_DIR/CatalogApp/Resources/.swiftlint.yml"
    scripts:
      - name: Install SPM Dependencies and SwiftLint
        script: |
          # Install SPM dependencies
          xcodebuild -resolvePackageDependencies -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME"
          
          swiftlint lint --config "$CONFIG_FILE" --strict
          
          if [[ "$(uname -m)" == arm64 ]]; then
              export PATH="/opt/homebrew/bin:$PATH"
          fi
          
          brew install swiftlint || brew upgrade swiftlint
          
          if which swiftlint > /dev/null; then
            # Run SwiftLint without --fix to identify issues
            swiftlint lint --config "$CONFIG_FILE"

            # Run SwiftLint with --fix to attempt automatic fixing
            swiftlint --config "$CONFIG_FILE" --fix

            # Run SwiftLint again to verify fixes
            swiftlint lint --config "$CONFIG_FILE"
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
      - name: Clean DerivedData
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - ul.frasha@gmail.com
