workflows:
  ios-project-debug:
    name: iOS debug
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: "CatalogApp.xcodeproj"
        XCODE_WORKSPACE: "CatalogApp.xcworkspace"
        XCODE_SCHEME: "CatalogApp"
        IOS_DEPLOYMENT_TARGET: "13.0"
    scripts:
      - name: Install Dependencies
        script: |
          pod install
      - name: Clean DerivedData
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - ul.frasha@gmail.com
